### ISSUE TITLE
Statistics of the whole company appear in the printed form

### ISSUE THREAD

**Issue by nvizzari** [BrunoGodefroy/theodo-form-printer#17]
Hi guys,

When I print the form for a BAM project, I see the statistics of all BAM projects on the form.
Besides not being eco-friendly (😄), it is confusing when reading the board.

Screenshots:

![image](https://user-images.githubusercontent.com/7067993/28660171-48f8efd4-72b2-11e7-84d8-ad871040c7c7.png)

**Comment by BrunoGodefroy** [comment]
@Samox has fixed that now
