### ISSUE TITLE
Questions order

### ISSUE THREAD

**Issue by Mx-Glitter** [BrunoGodefroy/theodo-form-printer#24]
Hello, for Sicara, we'd love to be able to change the order of the questions to have the recommendation question **before** the client's voice. I think modifying the order in [this file](https://github.com/BrunoGodefroy/theodo-form-printer/blob/gh-pages/src/config/forms/sicara.js) will work, but I can't test it right now, I'm gonna try it later on if you'd like @BrunoGodefroy 😉

**Comment by BrunoGodefroy** [comment]
@Triiistan Yes indeed, modifying that file is enough to change the questions order. I have deployed the updated order for the Sicara form 🙂

**Comment by Mx-Glitter** [comment]
Thx
